### ISSUE TITLE
Simultaneous use of from and into

### ISSUE THREAD

**Issue by vettich** [Zerounary/struct-convert#6]
It would be nice to be able to use from and into at once. I can't do that right now.

```rust
#[derive(Default, Convert)]
#[convert(from = "C")]
#[convert(into = "B")]
struct A {
    value: i64,
}

struct B {
    value: i64,
}

struct C {
    value: i64,
}

fn main() {
    let c = C { value: 8 };
    let a: A = c.into();
    let b: B = a.into();
}
```

will give an error

```
the trait bound `B: From<A>` is not satisfied
required for `A` to implement `Into<B>`
```

This is useful for intermediate "proxy" structures that need to receive input data and then transform it into output data, e.g. to "communicate" between different layers of the application

**Comment by Zerounary** [comment]
Support it since v1.2.5 👍

**Comment by Zerounary** [comment]
I have shown this example in the README file as the first example
